generic:
  error_prefix: "❗"
  done: "✅ Done"
  canceled: "Okay, closed."
  missing_template: "Let’s complete that: {missing}\nTry: {usage}\nExample: {example}"
  invalid_template: "Hmm, that didn’t look right — {error}\nTry: {usage}\nExample: {example}"
  header_help: "*Commands*"
  not_authorized: "Not authorized."
  unknown_input: "Didn’t catch that. Try /help"
  unknown_command: "Unknown command: `{cmd}`\nTry /help"

"/buy":
  prompt_usage: "Use: [qty] [symbol] [price_ccy]"
  success: "buy: *{symbol}* ×{qty} @ {price_ccy}"

"/sell":
  prompt_usage: "Use: [qty] [symbol] [price_ccy]"
  success: "sell: *{symbol}* ×{qty} @ {price_ccy}"

"/price":
  prompt_usage: "What symbols should I check? (e.g. NVDA AAPL)"
  success: "{text}"

"/fx":
  prompt_usage: "Use: [base] [quote] (e.g. USD EUR)"
  success: "{base}/{quote}: {rate}"

"/exit":
  prompt_usage: "Use: /exit to close the conversation"

"/portfolio":
  prompt_usage: "Use: /portfolio"
  empty: "No portfolio yet. Start with /add or /cash_add."
  header: "*Portfolio*"

"/add":
  prompt_usage: "Use: [qty] [symbol] [type]"

"/remove":
  prompt_usage: "Use: [symbol]"

"/cash":
  prompt_usage: "Use: /cash"

"/cash_add":
  prompt_usage: "Use: [amount]"

"/tx":
  prompt_usage: "Use: [n]"
  header: "*Transactions*"

"/portfolio_snapshot":
  prompt_usage: "Use: [period=d|w|m|y]"

"/portfolio_summary":
  prompt_usage: "Use: [period=d|w|m|y]"

"/portfolio_breakdown":
  prompt_usage: "Use: [period=d|w|m|y]"

"/portfolio_digest":
  prompt_usage: "Use: [period=d|w|m|y]"

"/portfolio_movers":
  prompt_usage: "Use: [period=d|w|m|y]"

"/allocation":
  prompt_usage: "Use: /allocation"

"/allocation_edit":
  prompt_usage: "Use: [etf,stocks,crypto]"

"/po_if":
  prompt_usage: "Use: [scope] [+x%|-x%]"

"/rename":
  prompt_usage: "Use: [symbol] [nickname]"
