version: "3.9"

services:
  n8n:
    image: n8nio/n8n:1.79.1
    container_name: n8n
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${TZ}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_TRUSTED_PROXIES=${N8N_TRUSTED_PROXIES}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED}
      - DB_SQLITE_POOL_SIZE=5
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - /opt/stack/config:/config:ro
    depends_on:
      fx:
        condition: service_healthy
      portfolio-logic:
        condition: service_started

volumes:
  n8n_data:
    external: true
    name: ${N8N_DATA_VOLUME:-n8n_n8n_data}
